article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "article"

urlpatterns = [
    path("dashboard/", views.dashboard,name = "dashboard"),
    path("addarticle/", views.addArticle,name = "addarticle"),
    path("article/<int:id>", views.detail,name = "detail"),
    path("update/<int:id>", views.updateArticle,name = "update"),
    path("", views.articles,name = "articles"),
    path("dashart",views.dashart,name = "dashart"),

    

]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('khRastR9584/', admin.site.urls),
    path('', views.index,name = "index"),
    path("articles/",include("article.urls")),
    path("magazines/",include("magazines.urls")),
    path("posts/",include("posts.urls")),
    path("user/",include("user.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

magazines/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = "magazines"

urlpatterns = [
    path("",views.magazines,name = "magazines"),
    path("addmagazine/",views.addMagazine,name = "addmagazine"),
    path("dashmag/", views.dashmag, name = "dashmag"),
    path("magazine/<int:id>", views.detail,name = "detail"),
    path("update/<int:id>",views.updateMagazine,name = "update",),
]

posts/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path("",views.posts,name = "posts"),
    path("addpost/",views.addPost,name = "addpost"),
    path("dashpost/",views.dashpost, name = "dashpost"),
    path("posts/<int:id>",views.detail,name = "detail"),
    path("delete/<int:id>",views.deletePost, name = "delete"),
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Article(models.Model):
    LANGUAGE_CHOICES = [
        ('EN', 'İngilizce'),
        ('ES', 'İspanyolca'),
        ('FR', 'Fransıca'),
        ('DE', 'Almanca'),
        ('TR', 'Türkçe'),
        # Diğer diller burada eklenebilir
    ]
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE,verbose_name="Yayıncı")
    publisher = models.CharField(max_length=50, verbose_name="Yazar İsmi",blank=True,null=True)
    publisher_detail= models.CharField(max_length=50, verbose_name="Yazar Detayları",blank=True,null=True)
    keywords = models.CharField(max_length=500,verbose_name="Anahtar Kelimeler",blank=True,null=True)
    source = RichTextField(verbose_name="Kaynakça",default="")
    article_language = models.CharField(max_length=2,choices=LANGUAGE_CHOICES,default="TR",verbose_name="Makale Dili")
    #foreignkey kullanarak author bilgisini kayıtlı kullanuculardan çekmesini istedik
    # models.CASCADE kullanarak eğer kullanıcı silinirse ona ait articleların da silinmesini sağladık
    # verbose_name methodunu kullanarakj değişken ismini belirledik
    article_type = models.CharField(max_length=50,verbose_name="Makale Türü",blank=True,null=True)
    title = models.CharField(max_length= 50, verbose_name= "Başlık")
    # max_lenght kullanarak kaç karakterlik bir yazı olacağını belirledik
    content = RichTextField(verbose_name="Özet")
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma Tarihi")
    # bu kod sayesinde uygulamanın tarihi otomatik olarak alabilmesini sağladık
    #article ismini title olarak göstermek için özel bir fonksiyon
    article_file = models.FileField(blank = True,null = True, verbose_name="Makalenin Kendisi")
    
    def __str__(self):
        return self.title
    

magazines/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.

class Magazine(models.Model):
    author = models.CharField(max_length=50,verbose_name="Yayımcı",blank=True,null=True)
    ıssn = models.CharField(max_length=100,verbose_name = "ISSN", blank= True,null = True)
    e_ıssn = models.CharField(max_length=100,verbose_name = "e-ISSN", blank = True, null= True)
    image = models.ImageField(blank=True,null=True, verbose_name = "Derginin Kapağı")
    file = models.FileField(blank= True, null = True, verbose_name = "Dergi")
    title = models.CharField(max_length=150, verbose_name="Derginin İsmi")
    about = RichTextField(verbose_name="Hakkında")
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Oluşturulma Tarihi")
    first_create = models.DateField(verbose_name="İlk Çıkış Tarihi")

    def __str__(self):
        return self.title
    

posts/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Post(models.Model):
    author = models.ForeignKey("auth.User",on_delete= models.CASCADE,verbose_name = "Paylaşan")
    yazar = models.CharField(max_length=25,verbose_name= "Yazar İsmi",blank=True,null=True)
    date = models.DateField(verbose_name= "Yazım Tarihi",blank=True,null=True)
    source = RichTextField(verbose_name = "Kaynakça",default="")
    imageOne = models.ImageField(blank=True,null=True, verbose_name = "Ek 1")
    descriptionOne = models.CharField(max_length=400, verbose_name="Ek 1 Açıklama",blank = True, null=True)
    imageTwo = models.ImageField(blank=True,null=True, verbose_name = "Ek 2")
    descriptionTwo = models.CharField(max_length=400, verbose_name="Ek 2 Açıklama",blank = True, null=True)
    imageThree = models.ImageField(blank=True,null=True, verbose_name = "Ek 3")
    descriptionThree = models.CharField(max_length=400, verbose_name="Ek 3 Açıklama",blank = True, null=True)

    title = models.CharField(max_length=50, verbose_name="Başlık")
    content = RichTextField(verbose_name= "İçerik")
    created_date = models.DateTimeField(auto_now_add=True, verbose_name = "Oluşturulma Tarihi")
    
    def __str__(self):
        return self.title

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["publisher",
                  "publisher_detail",
                  "keywords",
                  "source",
                  "article_language",
                  "article_type",
                  "title",
                  "content",
                  "article_file"]
        widgets = {
            'language': forms.Select(choices=Article.LANGUAGE_CHOICES),
        }

magazines/forms.py
from django import forms
from .models import Magazine

class MagazineForm(forms.ModelForm):
    class Meta:
        model = Magazine
        fields = [
            "author",
            "ıssn",
            "e_ıssn",
            "image",
            "file",
            "title",
            "about",
            "first_create",
        ]

posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
                  "yazar",
                  "title",
                  "content",
                  "source",
                  "imageOne",
                  "descriptionOne",
                  "imageTwo",
                  "descriptionTwo",
                  "imageThree",
                  "descriptionThree",
                  ]
        

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404
from .forms import ArticleForm
from .models import Article
from magazines.models import Magazine
from django.contrib import messages
from django.contrib.auth.decorators import login_required,user_passes_test
# Create your views here.

def isAdmin(user):
    return user.is_superuser

def articles(request):
    keyword = request.GET.get("keyword")

    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        
        return render(request,"articles.html",{"articles":articles})
    
    
    articles = Article.objects.all()
    return render(request,"articles.html",{"articles":articles})

def index(request):
    last_magazines = Magazine.objects.order_by("created_date")[:2]

    context = {
        "last_magazines": last_magazines    
    }
    return render(request,"index.html",context)

def about(request):
    return render(request,"about.html")

@login_required
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {
        "articles": articles
    }
    return render(request,"dashboard.html",context)

@user_passes_test(isAdmin)
def dashart(request):
    articles = Article.objects.all()
    context = {
        "articles": articles
    }
    return render(request,"dashart.html",context)

@user_passes_test(isAdmin)
def addArticle(request):
    art = "Makale"
    form = ArticleForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        article = form.save(commit= False)
        article.author = request.user
        article.save()

        messages.success(request,"Makale Başarıyla Oluşturuldu")
        return redirect("article:dashart")


    return render(request,"addarticle.html",{"form":form,"art":art})

def detail(request,id):
    # article = Article.objects.filter(id = id).first()
    article = get_object_or_404(Article,id = id)
    keywords = article.keywords.split(",")
    return render(request,"detail.html",{"article":article,"keywords":keywords})




@user_passes_test(isAdmin)
def updateArticle(request,id):

    art = "Makale"
    article = get_object_or_404(Article,id = id)
    form = ArticleForm(request.POST or None, request.FILES or None,instance=article)
    if form.is_valid():
        article = form.save(commit= False)
        article.author = request.user
        article.save()

        messages.success(request,"Makale Başarıyla Güncellendi")
        return redirect("article:dashart")

    return render(request,"update.html",{"form":form,"art":art})

magazines/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import MagazineForm
from .models import Magazine
from django.contrib import messages
from django.contrib.auth.decorators import login_required,user_passes_test

# Create your views here.
def isAdmin(user):
    return user.is_superuser
def magazines(request):
    keyword = request.GET.get("keyword")

    if keyword:
        magazines = Magazine.objects.filter(title__contains = keyword)
        return render(request,"magazines.html",{"magazines":magazines})
    
    magazines = Magazine.objects.all()
    return render(request,"magazines.html",{"magazines":magazines})

@user_passes_test(isAdmin)
def addMagazine(request):
    art = "Dergi"
    form = MagazineForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        form.save()

        messages.success(request,"Dergi Başarıyla Oluşturuldu")
        return redirect("magazines:dashmag")
    
    return render(request,"addarticle.html",{"form":form,"art":art})

@user_passes_test(isAdmin)
def dashmag(request):
    magazines = Magazine.objects.all()
    context = {
        "magazines": magazines
    }
    return render(request,"dashmag.html",context)

def detail(request,id):
    magazine = get_object_or_404(Magazine,id=id)
    return render(request,"magdetail.html",{"magazine":magazine})

@user_passes_test(isAdmin)
def updateMagazine(request,id):
    art = "Dergi"
    magazine = get_object_or_404(Magazine,id = id)
    form = MagazineForm(request.POST or None, request.FILES or None, instance = magazine)
    if form.is_valid():
        form.save()

        messages.success(request,"Dergi Başarıyla Güncellendi")
        return redirect("magazines:dashmag")
    return render(request,"update.html",{"form":form,"art":art})

posts/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import PostForm
from .models import Post
from django.contrib import messages
from django.contrib.auth.decorators import login_required,user_passes_test
import time
# Create your views here.
def isAdmin(user):
    return user.is_superuser




def posts(request):
    posts = Post.objects.all()
    return render(request,"posts.html",{"posts":posts})

@login_required
def addPost(request):
    post = "Gönderi"
    form = PostForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        post = form.save(commit= False)
        post.author = request.user
        post.save()

        messages.success(request,"Gönderin Paylaşıldı")
        return redirect("posts:dashpost")

    return render(request,"addpost.html",{"form":form,"post":post})
@login_required
def dashpost(request):
    if request.user.is_superuser :
        posts = Post.objects.all()


    else:
        posts = Post.objects.filter(author = request.user)
    context = {
    "posts":posts
    }
    return render(request,"dashpost.html",context)
    

def detail(request,id):
    post = get_object_or_404(Post,id=id)
    return render(request,"postdetail.html",{"post":post})

@user_passes_test(isAdmin)
def deletePost(request,id):
    post = get_object_or_404(Post,id=id)
    messages.success(request,"Gönderi Başarıyla Silindi")
    return redirect("posts:dashpost")

templates/addarticle.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>{{art}} Oluştur</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
                
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger"> {{art}} Ekle</button>
        </form>
        
    </div>
</div>
{% endblock body %}

templates/addpost.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
<div class = "row">
    <div class = "col-md-6 mx-auto">
        <h3>Gönderi Oluştur</h3>
        <hr>
        <form method = "post" enctype = "multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Gönderiyi Paylaş</button>
        </form>

    </div>

</div>


{% endblock  %}

templates/dashart.html
{% extends "layout.html" %}

{% block body %}

<div class="row mt-3">
    <div class="col-md-10 mx-auto">
            <h3>Makale Kontrol Paneli</h3>
            <hr>
            <a class = "btn btn-danger" href = "{% url 'article:addarticle' %}">Makale Ekle</a>
            <hr>
            {% if articles %}
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">id</th>
                        <th scope="col">Başlık</th>
                        <th scope="col">Yazar</th>
                        <th scope="col">Tarih</th>
                        <th scope="col">Güncelle</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for article in articles %}
                            <tr>
                                <th scope="row">{{article.id}}</th>
                                <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
                                <td>{{article.author.username}}</td>
                                <td>{{article.created_date}}</td>
                                <td><a href="{% url 'article:update' article.id %}" class = "btn btn-danger">Güncelle</a></td>
                            </tr>
                        {% endfor %}
                    <!--<tr>
                        <th scope="row">1</th>
                        <td>Mark</td>
                        <td>Otto</td>
                        <td>@mdo</td>
                    </tr> -->
                    
                    </tbody>
                </table>
    
            {% else %}
                <div class="alert alert-danger">
                    Henüz Bir Makaleniz Bulunmuyor
                </div>
            {% endif %}

    </div>
</div>


{% endblock  %}

templates/dashmag.html
{% extends "layout.html" %}

{% block body %}
<div class="row mt-3">
    <div class="col-md-10 mx-auto">
            <h3>Dergi Kontrol Paneli</h3>
            <hr>
            <a class = "btn btn-danger" href = "{% url 'magazines:addmagazine' %}">Dergi Ekle</a>
            <hr>
            {% if magazines %}
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">id</th>
                        <th scope="col">Başlık</th>
                        <th scope="col">Yazar</th>
                        <th scope="col">Tarih</th>
                        <th scope="col">Güncelle</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for magazine in magazines %}
                            <tr>
                                <th scope="row">{{magazine.id}}</th>
                                <td><a href="{% url 'magazines:detail' magazine.id %}">{{magazine.title}}</a></td>
                                <td>{{magazine.author.username}}</td>
                                <td>{{magazine.created_date}}</td>
                                <td><a href="{% url 'magazines:update' magazine.id %}" class = "btn btn-danger">Güncelle</a></td>
                            </tr>
                        {% endfor %}
                    <!--<tr>
                        <th scope="row">1</th>
                        <td>Mark</td>
                        <td>Otto</td>
                        <td>@mdo</td>
                    </tr> -->
                    
                    </tbody>
                </table>
    
            {% else %}
                <div class="alert alert-danger">
                    Henüz Bir Derginiz Bulunmuyor
                </div>
            {% endif %}
    </div>
</div>
{% endblock body %}

templates/dashpost.html
{% extends "layout.html" %}

{% block body %}


<div class = "row mt-3">
    <div class = "col-md-10 mx-auto">
        <h3>Gönderi Kontrol Paneli</h3>
        <hr>
        <a class = "btn btn-danger" href = "{%url 'posts:addpost'%}">Gönderi Paylaş</a>
        <hr>
        {% if posts %}
            <table class = "table">
                <thead>
                    <tr>
                        <th scope="col">id</th>
                        <th scope="col">Başlık</th>
                        <th scope="col">Yazar</th>
                        <th scope="col">Tarih</th>
                        {% if user == superUser %}
                        <th scope="col">Sil</th>
                        {% endif %}

                    </tr>
                </thead>
                <tbody>
                    {% for post in posts %}
                        <tr>
                            <th scope="row">{{post.id}}</th>
                            <td><a href="{% url 'posts:detail' post.id %}">{{post.title}}</a></td>
                            <td>{{post.author.username}}</td>
                            <td>{{post.created_date}}</td>


                        </tr>
                    {% endfor %}
                <!--<tr>
                    <th scope="row">1</th>
                    <td>Mark</td>
                    <td>Otto</td>
                    <td>@mdo</td>
                </tr> -->
                
                </tbody>
            </table>
        {% else %}
            <div class="alert alert-danger">
                Henüz Bir Gönderi Paylaşmadınız 
            </div>
        {% endif %}

    </div>

</div>




{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Etügen - Tarihinizi Yazmaya Başlayın</title>
    <meta name="description" content="Etügen, Erciyes Üniversitesi öğrencilerinin tarihi makale, dergi ve araştırma yazılarını paylaştığı bir platformdur. Siz de yazılarınızı paylaşmak için bize ulaşabilirsiniz.">
    <meta name="keywords" content="Etügen, Erciyes Üniversitesi, tarihi makaleler, araştırma yazıları, dergi yazıları, öğrenci platformu, tarihi araştırma, yazı paylaşımı, makale yayınlama">

</head>
<body class = "d-flex flex-column min-vh-100">
  
  {% block navbar %}
    {% include "includes/navbar.html" %}
  {% endblock navbar %}


    
        {% if messages %}
                {% for message in messages %}
                    {% if message.tags == "info" %}
                        <div class="alert alert-danger">{{ message }}</div>
                    {% else %}
                        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                    {% endif %}
                {% endfor %}
        {% endif %}
        
    
        {% block body %}
            
        {% endblock body %}


        <!-- Remove the container if you want to extend the Footer to full width. -->
    <div style = "height:10px;"></div>
{% block footer %}




{% endblock footer %}



<script src = "{% static 'js/bootstrap.min.js' %}"></script>
    <script src = "{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>

</body>
</html>

templates/login.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Giriş Yap</h3>
        <hr>
        <form method = "post">
            {% csrf_token %}

            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger"> Giriş Yap</button>
        </form>
        
    </div>
</div>

{% endblock body %}

templates/magazines.html
{% extends "layout.html" %}



{% block body %}
{% comment %} <div class="row">
    <div class="col-md-3 mx-auto">
        <div class="col-lg-8 mt-4">

            <h3>Dergiler</h3>
            <hr>
            <form class="d-flex">
                {% csrf_token %}
                <input class="form-control me-2" name = "keyword" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</div>
<hr> {% endcomment %}
<div class="row">
    <div class="col-md-3 mx-auto">
        <div class="col-lg-8 mt-4">
            <h3>Dergiler</h3>
        </div>
    </div>
    <hr>
</div>
<div class="row">
    <div class="col-md-3 mx-auto">
        <div class="col-lg-16">
            <form class="d-flex">
                {% csrf_token %}
                <input class="form-control me-2" name = "keyword" type="search" placeholder="Dergi Ara" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Ara</button>
            </form>
        </div>
    </div>
</div>

<hr>
{% if magazines %}
<div class="row">
    <div class = "col-lg-10 col-lg-10 col-md-8 col-xs-1 col col mx-auto">
        <div class="row row-cols-1 row-cols-xl-4 row-cols-lg-3 row-cols-md-2 row-cols-1 row-col-ms-2 g-3">
            {% for magazine in magazines %}
            <div class="col">
                <div class="card" style = "height : 500px;">
                    <div style = "margin: 30px 30px 0px 30px; height : 300px;">
                        {% if magazine.image %}
                        <a href = "{% url 'magazines:detail' magazine.id %}">
                            <img src="{{magazine.image.url}}" class="card-img-top"
                            alt="Skyscrapers" style="width: 100%; height: 300px;">
                        </a>
                        {% endif %}
                    </div>
                    <hr>
                    <div class="card-body">
                        <a href="{% url 'magazines:detail' magazine.id %}" style= "text-decoration: none;" >
                            <h5 class="card-title" style = "text-align:center; color: #093777;">{{magazine.title}}</h5>
                        </a>
                    </div>
                    <div class="card-footer">
                        <div class="badge bg-secondary text-decoration-none link-light" style = "float:left;"href="">e-ISSN: {{magazine.e_ıssn}}</div>
                        <div class="badge bg-secondary text-decoration-none link-light" style = "float:right;" href="">ISSN: {{magazine.ıssn}}</div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<div style= "height:100px;">

</div>
{% else %}

<div class="row" style: "max-width: 100%;">
    <div class="col-md-8 offset-md-4">
        <div class="col-lg-8">
            <div class = "alert alert-danger">
                Henüz Bir Dergi Yayınlamadık. Ziyaretiniz İçin Teşekkür Ederiz.
            </div>
        </div>
    </div>
</div>

{% endif %}

{% endblock body %}

templates/posts.html
{% extends "layout.html" %}
{% block navbar %}

{% endblock navbar %}



{% block body %}
{% load static %}
<div style = "margin:10px 80px 0px 0px;">
    <div class="d-flex justify-content-around">
        <a class="navbar-brand" href="{% url 'index' %}">
            <img src="{% static "images/etügen5.png" %}" alt="">
        </a>
        <h3>Gönderiler</h3>
        <h3></h3>
        {% comment %} <a class = "btn btn-danger" href = "{%url 'posts:addpost'%}">Gönderi Paylaş</a> {% endcomment %}
    </div>

</div>

<hr>
{% if posts %}

{% for post in posts %}

<a href="{%url 'posts:detail' post.id%}">
    <div class="row" style = "max-width: 100%;">
        <div class="col-lg-5 col-lg-19 col-md-8 col-xs-1 mx-auto">
            <div class="card" style="margin-bottom: 20px; width: 100%;">
                <div class="card-body">
                    <h6 class="card-subtitle mb-2 mt-2 text-muted">{{post.author}}</h6>
                    
                    <a style = "text-decoration: none;" href="{% url 'posts:detail' post.id %}">
                        <h5 class="card-title"> {{post.title}}</h5>
                    </a>
                    <hr>
                    <p class="card-text">{{post.content|safe|truncatewords:98}}</p>
                    <hr>
                    <div class="d-flex justify-content-between">
                        <div class="text-muted fst-italix mb-2">siteye eklenme tarihi {{post.created_date}}</div>
                        <p></p>
                        <h6>
                            {{post.yazar}}
                        </h6>
                    </div>
                    {% comment %} <div class="text-muted fst-italix mb-2">siteye eklenme tarihi {{post.created_date}}</div> {% endcomment %}
                </div>
            </div>
        </div>
    </div>
</a>

{% endfor %}

{% else %}
<div class="row">
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
            <div class = "alert alert-danger">
                Gönderi Bulunamadı
            </div>
        </div>
    </div>
</div>

{% endif %}

{% endblock  %}

templates/register.html
{% extends "layout.html" %}


{% block body %}

{% load crispy_forms_tags %}
<div class="row">
    <div class="col-md-3 mx-auto mt-4">

        <h3>Kayıt Ol</h3>
        <hr>
        
        <form method = "post">
            {% csrf_token %}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Kayıt Ol</button>
        </form>
        
    </div>
</div>


{% endblock body %}

templates/update.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>{{art}} Güncelle</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger"> {{art}} Güncelle</button>
        </form>
        
    </div>
</div>
{% endblock body %}

templates/updatemag.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Dergi Güncelle</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger"> Dergi Güncelle</button>
        </form>
        
    </div>
</div>
{% endblock body %}